// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderProcessing.Infrastructure.Persistence;

#nullable disable

namespace OrderProcessing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkOrderProcessingDbContext))]
    [Migration("20260506000410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderProcessing.Domain.Models.Materials.Product", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.Materials.StockKeepingUnit", b =>
                {
                    b.Property<Guid>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("product_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SerialNumber");

                    b.HasIndex("product_item_id");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderItemQty")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ordered_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ordered_item_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.WorkOrderStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "ChangedUtc");

                    b.ToTable("work_order_state_history", (string)null);
                });

            modelBuilder.Entity("work_order_skus", b =>
                {
                    b.Property<Guid>("AssignedStockSerialNumber")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignedStockSerialNumber", "WorkOrderId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_skus");
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.Materials.StockKeepingUnit", b =>
                {
                    b.HasOne("OrderProcessing.Domain.Models.Materials.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.WorkOrder", b =>
                {
                    b.HasOne("OrderProcessing.Domain.Models.Materials.Product", "OrderedItem")
                        .WithMany()
                        .HasForeignKey("ordered_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderedItem");
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.WorkOrderStateHistory", b =>
                {
                    b.HasOne("OrderProcessing.Domain.Models.WorkOrder", "WorkOrder")
                        .WithMany("StateHistory")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("work_order_skus", b =>
                {
                    b.HasOne("OrderProcessing.Domain.Models.Materials.StockKeepingUnit", null)
                        .WithMany()
                        .HasForeignKey("AssignedStockSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderProcessing.Domain.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderProcessing.Domain.Models.WorkOrder", b =>
                {
                    b.Navigation("StateHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
